### ISSUE TITLE
Resource files (images) are not included into Jar

### ISSUE THREAD

**Issue by maxim-kukushkin** [Borisvl/JBIG2-Image-Decoder#3]
After building the library with "ant" and trying to run the viewer from the examples, the following exception is thrown:

$ java -cp jbig2.jar org.jpedal.jbig2.examples.viewer.JBIG2Viewer
java.lang.NullPointerException
    at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
    at org.jpedal.jbig2.examples.viewer.JBIG2Viewer.setUpToolbar(Unknown Source)
    at org.jpedal.jbig2.examples.viewer.JBIG2Viewer.<init>(Unknown Source)
    at org.jpedal.jbig2.examples.viewer.JBIG2Viewer.main(Unknown Source)

This happens because the resource files are not added to the output Jar file

**Comment by maxim-kukushkin** [comment]
Following patch fixes the problem (also leaving an option to build library only, without the examples):

diff --git a/build.xml b/build.xml
index 85d360c..991ede5 100644
--- a/build.xml
+++ b/build.xml
@@ -2,6 +2,7 @@
 
        <property name="build" value="build"/>
        <property file="build.properties"/>
+       <property name="res.path" value="org/jpedal/jbig2/examples/viewer/res"/>
        
        <target name="clean">
                <delete dir="${build}"/>
@@ -12,15 +13,25 @@
                <mkdir dir="${build}"/>
        </target>       
        
-       <target name="compile" depends="init">
-               
+       <target name="compile" depends="init" unless="libonly">
                <javac srcdir="src" destdir="${build}">
                </javac>
-       </target>       
+       </target>
+
+       <target name="resources" depends="compile" unless="libonly">
+               <copy todir="build/${res.path}">
+                       <fileset dir="src/${res.path}"/>
+               </copy>
+       </target>
+       
+       <target name="compile-lib" depends="init" if="libonly">
+               <javac srcdir="src" destdir="${build}" excludes="org/jpedal/jbig2/examples/**">
+               </javac>
+       </target>
        
-       <target name="jar" depends="compile">
+       <target name="jar" depends="resources,compile-lib">
                
                <jar basedir="${build}" destfile="jbig2.jar"/>
        </target>
        
-</project>
\ No newline at end of file
+</project>

**Comment by maxim-kukushkin** [comment]
I have a patch for build.xml, but cannot find out how to attach it
